[build]
  base = "."
  command = "python -m pip install --upgrade pip && pip install -r api/requirements.txt && cd app && npm install && npm run build"
  publish = "app/out"

[build.environment]
  NETLIFY_USE_LEGACY_BUILD_IMAGE = "true"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"
  PYTHON_RUNTIME = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"

[dev]
  command = "cd app && npm run dev"
  port = 3000
  publish = "app" 